<a href="https://colab.research.google.com/github/Quenassier/11.09-2023/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [33]:

    ptd1 = pd.read_csv('part_01.csv')
    ptd2 = pd.read_csv('part_02.csv')
    ptd3 = pd.read_csv('part_03.csv')
    ptd4 = pd.read_csv('part_04.csv')
    ptd5 = pd.read_csv('part_05.csv')
    ptd6 = pd.read_csv('part_06.csv')
    ptd7 = pd.read_csv('part_07.csv')
    ptd8 = pd.read_csv('part_08.csv')
    ptd9 = pd.read_csv('part_09.csv')
    ptd10 = pd.read_csv('part_10.csv')
    ptd11 = pd.read_csv('part_11.csv')
    ptd12 = pd.read_csv('part_12.csv')

In [34]:
  ptds = [ptd1, ptd2, ptd3, ptd4, ptd5, ptd6, ptd7, ptd8, ptd9, ptd10, ptd11, ptd12]

In [35]:
db1 = pd.concat([ptd1, ptd9], ignore_index=True)
db2 = pd.concat([ptd2, ptd11], ignore_index=True)
db3 = pd.concat([ptd4, ptd7], ignore_index=True)
db4 = pd.concat([ptd5, ptd12], ignore_index=True)
db5 = pd.concat([ptd6, ptd10], ignore_index=True)
db6 = pd.concat([ptd3, ptd8], ignore_index=True)

In [36]:
dbraw = [db1, db2, db3, db4, db5, db6]

In [37]:
db = db1

In [38]:
for i in range(1, len(dbraw)):
      db = db.merge(dbraw[i], left_on='ID', right_on='ID')

In [39]:
db.drop_duplicates()

,ID,AMOUNT_RUB_ATM_PRC,AMOUNT_RUB_CLO_PRC,AMOUNT_RUB_NAS_PRC,AMOUNT_RUB_SUP_PRC,CNT_TRAN_ATM_TENDENCY1M,CNT_TRAN_ATM_TENDENCY3M,CNT_TRAN_AUT_TENDENCY1M,CNT_TRAN_AUT_TENDENCY3M,CNT_TRAN_CLO_TENDENCY1M,...,LDEAL_TENOR_MAX,LDEAL_TENOR_MIN,LDEAL_USED_AMT_AVG_YQZ,LDEAL_USED_AMT_AVG_YWZ,LDEAL_YQZ_CHRG,LDEAL_YQZ_COM,LDEAL_YQZ_PC,MAX_PCLOSE_DATE,MED_DEBT_PRC_YQZ,MED_DEBT_PRC_YWZ
0,358628,0.914453,0.003802,0.000000,0.030183,0.216216,0.540541,0.333333,0.333333,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,528730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,160451,0.989403,0.000239,0.000992,0.000765,NaN,0.312500,NaN,0.333333,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,210467,0.561584,0.000000,0.016932,0.009256,NaN,0.600000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,292486,0.201789,0.147567,0.033131,0.165119,0.142857,1.000000,NaN,0.400000,0.266667,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
355185,429336,0.689106,0.000000,0.000000,0.182250,0.464286,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355186,434397,0.804371,0.028065,0.009167,0.073858,0.181818,0.848485,0.076923,1.000000,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,0.0
355187,151916,0.143807,0.026907,0.000000,0.122340,NaN,NaN,NaN,NaN,0.250000,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,0.0
355188,165248,0.268573,0.054830,0.000000,0.100210,0.800000,0.800000,NaN,NaN,0.333333,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355189,192800,0.995660,0.000000,0.000000,0.000000,0.333333,0.333333,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
db.APP_COMP_TYPE.where(db.APP_COMP_TYPE.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
db.APP_COMP_TYPE = db.APP_COMP_TYPE.str.lower()

In [42]:
print(list(db.APP_COMP_TYPE.unique()))
dbTrans = db.T
dbTrans = dbTrans.drop_duplicates()
db = dbTrans.T

[nan, 'private', 'state', 'inter', 'ip']

In [46]:
db = db.sort_values('ID')

In [43]:
print(db.head(10))

       ID AMOUNT_RUB_ATM_PRC AMOUNT_RUB_CLO_PRC AMOUNT_RUB_NAS_PRC  \
0  358628           0.914453           0.003802                0.0
1  528730                NaN                NaN                NaN
2  160451           0.989403           0.000239           0.000992
3  210467           0.561584                0.0           0.016932
4  292486           0.201789           0.147567           0.033131
5  211110           0.909531           0.051183                0.0
6  333131           0.485581           0.008142                0.0
7  549028            0.73862           0.020976           0.005257
8  274285           0.998698                0.0                0.0
9  577671                0.0                0.0           0.036643

  AMOUNT_RUB_SUP_PRC CNT_TRAN_ATM_TENDENCY1M CNT_TRAN_ATM_TENDENCY3M  \
0           0.030183                0.216216                0.540541
1                NaN                     NaN                     NaN
2           0.000765                     NaN                  0.3125
3           0.009256                     NaN                     0.6
4           0.165119                0.142857                     1.0
5           0.023359                0.238095                0.571429
6           0.045329                     0.4                     0.7
7           0.074851                 0.26087                0.478261
8                0.0                0.653846                     1.0
9           0.150664                     NaN                     NaN

  CNT_TRAN_AUT_TENDENCY1M CNT_TRAN_AUT_TENDENCY3M CNT_TRAN_CLO_TENDENCY1M  \
0                0.333333                0.333333                     NaN
1                     NaN                     NaN                     NaN
2                     NaN                0.333333                     NaN
3                     NaN                     NaN                     NaN
4                     NaN                     0.4                0.266667
5                     NaN                     NaN                     NaN
6                     0.5                0.666667                0.285714
7                     0.5                   0.625                     1.0
8                     NaN                     NaN                     NaN
9                     NaN                     NaN                     NaN

   ... LDEAL_TENOR_MAX LDEAL_TENOR_MIN LDEAL_USED_AMT_AVG_YQZ  \
0  ...             NaN             NaN                    NaN
1  ...             NaN             NaN                    NaN
2  ...             NaN             NaN                    NaN
3  ...             NaN             NaN                    NaN
4  ...             NaN             NaN                    NaN
5  ...             NaN             NaN                    NaN
6  ...             NaN             NaN                    NaN
7  ...             NaN             NaN                    NaN
8  ...             NaN             NaN                    NaN
9  ...             NaN             NaN                    NaN

  LDEAL_USED_AMT_AVG_YWZ LDEAL_YQZ_CHRG LDEAL_YQZ_COM LDEAL_YQZ_PC  \
0                    NaN            NaN           NaN          NaN
1                    NaN            NaN           NaN          NaN
2                    NaN            NaN           NaN          NaN
3                    NaN            NaN           NaN          NaN
4                    1.0            NaN           NaN          NaN
5                    NaN            NaN           NaN          NaN
6                    NaN            NaN           NaN          NaN
7                    NaN            NaN           NaN          NaN
8                    NaN            NaN           NaN          NaN
9                    1.0            NaN           NaN          NaN

  MAX_PCLOSE_DATE MED_DEBT_PRC_YQZ MED_DEBT_PRC_YWZ
0             NaN              NaN              NaN
1             NaN              NaN              NaN
2             NaN              NaN              NaN
3             NaN              NaN              NaN
4             NaN              NaN              0.0
5             NaN              NaN              NaN
6             NaN              NaN              NaN
7             NaN              NaN              NaN
8             NaN              NaN              NaN
9             NaN              NaN              0.0

[10 rows x 105 columns]

In [44]:
print("Rows: " + str(db.shape[0]) + " Cols: " + str(db.shape[1]))

Rows: 355190 Cols: 105

In [45]:
print(db['CLNT_TRUST_RELATION'].unique)
print(db['APP_MARITAL_STATUS'].unique)
print(db['CLNT_JOB_POSITION'].unique)

<bound method Series.unique of 0            NaN
1         FRIEND
2            NaN
3         MOTHER
4            NaN
           ...
355185       NaN
355186       NaN
355187    FRIEND
355188       NaN
355189       NaN
Name: CLNT_TRUST_RELATION, Length: 355190, dtype: object>
<bound method Series.unique of 0         NaN
1           M
2           M
3           V
4         NaN
         ...
355185    NaN
355186    NaN
355187      V
355188    NaN
355189    NaN
Name: APP_MARITAL_STATUS, Length: 355190, dtype: object>
<bound method Series.unique of 0                          предприниматель
1                         Начальник отдела
2                                      NaN
3                                   БАРМЕН
4                       старший специалист
                        ...
355185                                 NaN
355186                      Мастер Участка
355187                         Консультант
355188                                 NaN
355189    монитор клинических исследований
Name: CLNT_JOB_POSITION, Length: 355190, dtype: object>